name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ruby Setup with test version
      uses: eregon/use-ruby-action@master # defaults to .ruby-version file in repository
      # uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

